services:
  mongodb:
    image: mongo:latest
    container_name: streetlight-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: streetlight-backend
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: streetlight-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongodb_data: